name: list_of_stuff
description: A new Flutter application.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  gooey_carousel: ^0.1.2
  shared_preferences: ^2.0.5
  intl: 0.15.7
  provider: ^4.3.3
  custom_radio_grouped_button: ^1.0.6+1
  hive: ^2.0.4
  hive_flutter: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  hive_generator: ^1.1.0
  build_runner: ^2.0.3
  path_provider: ^2.0.1

flutter_icons:
  android: true
  image_path_android: "./assets/images/foreground.png"
  image_path_ios: "./assets/images/foreground.png"
  adaptive_icon_foreground: "./assets/images/foreground.png"
  adaptive_icon_background: "./assets/images/background.png"

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: koho
      fonts:
        - asset: assets/fonts/KoHo-ExtraLight.ttf
        - asset: assets/fonts/KoHo-Light.ttf
        - asset: assets/fonts/KoHo-Regular.ttf
        - asset: assets/fonts/KoHo-Medium.ttf
        - asset: assets/fonts/KoHo-Bold.ttf
